matrix:
  include:
    - stage: Tox
      language: 'python'
      python:
        - "3.6"
      install: pip install tox-travis
      script: tox
    - stage: Vue
      language: 'node_js'
      node_js:
        - 10
      python:
        - "3.6"
      install:
        - pip install -r requirements.txt --user
        - cd src/main/vue/client/todo/
        - npm ci
      script:
        - python src/main/server/server.py &
        - npm run dev &
        - npm test